export const HORSE_BREEDS = [
  'Akhal-Teke',
  'American Cream Draft',
  'American Miniature Horse',
  'American Paint Horse',
  'American Saddlebred',
  'Andaluz',
  'Anglo-Árabe',
  'Appaloosa',
  'Árabe',
  'Ardennais',
  'Baixadeiro',
  'Barb',
  'Belgian Draft',
  'Brasileiro de Hipismo',
  'Bretão',
  'Campolina',
  'Campeiro',
  'Cavalo de Przewalski',
  'Clydesdale',
  'Connemara',
  'Crioulo',
  'Dales Pony',
  'Dartmoor',
  'Exmoor',
  'Falabella',
  'Fjord',
  'Friesian',
  'Gypsy Vanner',
  'Hackney',
  'Haflinger',
  'Hanoveriano',
  'Holsteiner',
  'Icelandic',
  'Irish Cob',
  'Irish Sport Horse',
  'Kathiawari',
  'Kentucky Mountain Saddle Horse',
  'Lipizzaner',
  'Lusitano',
  'Mangalarga',
  'Mangalarga Marchador',
  'Marajoara',
  'Marwari',
  'Missouri Fox Trotter',
  'Morgan',
  'Mustang',
  'Nordestino',
  'Oldenburg',
  'Paint Horse',
  'Pantaneiro',
  'Paso Fino',
  'Percheron',
  'Peruvian Paso',
  'Piquira',
  'Pônei Brasileiro',
  'Pônei de Shetland',
  'Puro Sangue Inglês',
  'Quarto de Milha',
  'Rocky Mountain Horse',
  'Selle Français',
  'Shire',
  'Sorraia',
  'Standardbred',
  'Tennessee Walking Horse',
  'Trakehner',
  'Warmblood Holandês',
  'Welsh Cob',
  'Welsh Pony',
] as const

export type HorseBreed =
  (typeof HORSE_BREEDS)[number]